# Generated by Django 5.0.6 on 2024-07-13 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reclamacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=100)),
                ("canal_pago", models.CharField(max_length=100)),
                ("fecha_operacion", models.DateField()),
                ("tarjeta", models.CharField(max_length=100)),
                ("traza", models.CharField(max_length=100)),
                ("autorizo_operacion", models.CharField(max_length=100)),
                ("numero_referencia", models.CharField(max_length=100)),
                (
                    "importe_operacion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "importe_reclamacion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("motivo_reclamacion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("registrada", "Registrada"),
                            ("espera_banco", "En espera de respuesta del banco"),
                            (
                                "espera_remesador",
                                "En espera de respuesta del remesador",
                            ),
                            ("procesada", "Procesada"),
                        ],
                        default="registrada",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
